name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Create storage folder
        run: mkdir -p storage

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          bin/rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: |
          export RUBYOPT=-W0
          bundle exec rspec
